# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: def34dd399aed2836a5c386ed31f9688051a7a023fced38e002ed3bbaa14b1391520323d95f896bdca8aaddc70a22e921569f84908d853dc826c651040231e24

test:
  secret_key_base: ce9c4d4a18f679120da849debc68841c56d1a02b01a2932a81f1eca929583932f682017bc7d8a6ac7b577d7f720d95b488b1fddf63775631c91e9fa6f5b15a52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
